Repository BlogSquad/my_blog, pull requests merged in 2022-06, with the labels that each got.

#90 GitHub redirect url remove
  src/main/java/project/myblog/auth/dto/AuthProperties.java
Labels: bug

#91 readme 정리
  README.md
Labels: documentation

#92 travis 초기 설정
  .travis.yml
Labels: etc

#102 Travis CI AWS S3 설정
  .travis.yml
Labels: etc

#103 운영 Travis CI AWS S3 설정
  .travis.yml
Labels: etc, prod

#105 Travis에서 AWS S3에 deploy 불가 수정
  .travis.yml
Labels: etc, hotfix

#106 Travis CI, S3, CodeDeploy 세팅
  .travis.yml
  appspec.yml
Labels: etc

#107 운영 Travis CI, S3, CodeDeploy 세팅
  .travis.yml
  appspec.yml
Labels: etc, prod

#109 AWS CodeDeploy에 배포 안되는 현상 수정
  .travis.yml
  appspec.yml
Labels: hotfix
