Repository BlogSquad/my_blog, pull requests merged in 2022-04, with the labels that each got.

#6 네이버 로그인
  build.gradle
  src/docs/asciidoc/index.adoc
  src/main/java/project/myblog/Application.java
  src/main/java/project/myblog/authentication/Login.java
  src/main/java/project/myblog/authentication/LoginMemberArgumentResolver.java
  src/main/java/project/myblog/authentication/LogoutInterceptor.java
  src/main/java/project/myblog/authentication/OAuthAuthentication.java
  src/main/java/project/myblog/authentication/OAuthAuthenticationInterceptor.java
  src/main/java/project/myblog/authentication/session/NaverOAuthSessionAuthentication.java
  src/main/java/project/myblog/authentication/session/OAuthSessionAuthentication.java
  src/main/java/project/myblog/authorization/AuthorizationInterceptor.java
  src/main/java/project/myblog/config/WebConfig.java
  src/main/java/project/myblog/domain/Member.java
  src/main/java/project/myblog/exception/AuthenticationException.java
  src/main/java/project/myblog/exception/AuthorizationException.java
  src/main/java/project/myblog/exception/ErrorController.java
  src/main/java/project/myblog/exception/ExceptionController.java
  src/main/java/project/myblog/oauth/AuthProperties.java
  src/main/java/project/myblog/oauth/NaverAccessToken.java
  src/main/java/project/myblog/repository/MemberRepository.java
  src/main/java/project/myblog/service/AuthService.java
  src/main/java/project/myblog/web/MemberController.java
  src/main/java/project/myblog/web/dto/LoginMember.java
  src/main/java/project/myblog/web/dto/MemberResponse.java
  src/main/java/project/myblog/web/dto/OAuthApiResponse.java
  src/main/resources/application-oauth.yml
  src/main/resources/application.yml
  src/main/resources/static/docs/index.html
  src/test/java/project/myblog/ApplicationTests.java
  src/test/java/project/myblog/acceptance/AcceptanceTest.java
  src/test/java/project/myblog/acceptance/auth/AuthAcceptanceTest.java
  src/test/java/project/myblog/acceptance/auth/AuthSteps.java
  src/test/java/project/myblog/config/TestWebConfig.java
  src/test/java/project/myblog/documentation/Documentation.java
  src/test/java/project/myblog/documentation/auth/AuthDocumentation.java
  src/test/java/project/myblog/utils/DatabaseCleanup.java
Labels: feat

#8 깃허브 로그인 개발
  src/main/java/project/myblog/auth/authentication/Logout.java
  src/main/java/project/myblog/auth/authentication/OAuthAuthentication.java
  src/main/java/project/myblog/auth/authentication/intercpetor/LogoutInterceptor.java
  src/main/java/project/myblog/auth/authentication/intercpetor/OAuthAuthenticationInterceptor.java
  src/main/java/project/myblog/auth/authentication/session/OAuthSessionAuthentication.java
  src/main/java/project/myblog/auth/authentication/session/SessionLogout.java
  src/main/java/project/myblog/auth/authentication/session/github/GithubOAuthSessionAuthentication.java
  src/main/java/project/myblog/auth/authentication/session/naver/NaverOAuthSessionAuthentication.java
  src/main/java/project/myblog/auth/authorization/interceptor/AuthorizationInterceptor.java
  src/main/java/project/myblog/auth/dto/AuthProperties.java
  src/main/java/project/myblog/auth/dto/Login.java
  src/main/java/project/myblog/auth/dto/LoginMember.java
  src/main/java/project/myblog/auth/dto/LoginMemberArgumentResolver.java
  src/main/java/project/myblog/auth/dto/OAuthApiResponse.java
  src/main/java/project/myblog/auth/dto/SocialType.java
  src/main/java/project/myblog/auth/dto/github/GithubAccessToken.java
  src/main/java/project/myblog/auth/dto/github/GithubOAuthApiResponse.java
  src/main/java/project/myblog/auth/dto/naver/NaverAccessToken.java
  src/main/java/project/myblog/auth/dto/naver/NaverOAuthApiResponse.java
  src/main/java/project/myblog/config/WebConfig.java
  src/main/java/project/myblog/service/AuthService.java
  src/main/java/project/myblog/web/MemberController.java
  src/main/resources/application-oauth.yml
  src/test/java/project/myblog/acceptance/auth/AuthAcceptanceTest.java
  src/test/java/project/myblog/acceptance/auth/AuthSteps.java
  src/test/java/project/myblog/config/TestWebConfig.java
Labels: feat

#11 etc/패키지 구조 개선
  src/main/java/project/myblog/authentication/Login.java
  src/main/java/project/myblog/authentication/LoginMemberArgumentResolver.java
  src/main/java/project/myblog/authentication/LogoutInterceptor.java
  src/main/java/project/myblog/authentication/OAuthAuthentication.java
  src/main/java/project/myblog/authentication/OAuthAuthenticationInterceptor.java
  src/main/java/project/myblog/authentication/session/NaverOAuthSessionAuthentication.java
  src/main/java/project/myblog/authentication/session/OAuthSessionAuthentication.java
  src/main/java/project/myblog/authorization/AuthorizationInterceptor.java
  src/main/java/project/myblog/oauth/AuthProperties.java
  src/main/java/project/myblog/oauth/NaverAccessToken.java
  src/main/java/project/myblog/service/AuthService.java
  src/main/java/project/myblog/web/dto/LoginMember.java
Labels: refactor

#13 인가 인터셉터 JWT 확장 고려하여 개선하기
  src/main/java/project/myblog/auth/authorization/Authorization.java
  src/main/java/project/myblog/auth/authorization/interceptor/AuthorizationInterceptor.java
  src/main/java/project/myblog/auth/authorization/session/SessionAuthorization.java
  src/main/java/project/myblog/config/WebConfig.java
  src/test/java/project/myblog/config/TestWebConfig.java
Labels: feat

#20 내 회원 정보 수정 개발
  build.gradle
  src/docs/asciidoc/index.adoc
  src/main/java/project/myblog/auth/authentication/OAuthAuthentication.java
  src/main/java/project/myblog/auth/authentication/session/github/GithubOAuthSessionAuthentication.java
  src/main/java/project/myblog/auth/authentication/session/naver/NaverOAuthSessionAuthentication.java
  src/main/java/project/myblog/auth/dto/LoginMember.java
  src/main/java/project/myblog/domain/Member.java
  src/main/java/project/myblog/exception/ExceptionController.java
  src/main/java/project/myblog/service/member/MemberService.java
  src/main/java/project/myblog/web/MemberController.java
  src/main/java/project/myblog/web/dto/member/MemberBlank.java
  src/main/java/project/myblog/web/dto/member/request/MemberIntroductionRequest.java
  src/main/java/project/myblog/web/dto/member/request/MemberSubjectRequest.java
  src/main/java/project/myblog/web/dto/member/response/MemberResponse.java
  src/main/resources/static/docs/index.html
  src/test/java/project/myblog/acceptance/auth/AuthAcceptanceTest.java
  src/test/java/project/myblog/acceptance/auth/AuthSteps.java
  src/test/java/project/myblog/acceptance/member/MemberAcceptance.java
  src/test/java/project/myblog/acceptance/member/MemberSteps.java
  src/test/java/project/myblog/acceptance/member/MemberStepsAssert.java
  src/test/java/project/myblog/acceptance/member/MemberStepsRequest.java
  src/test/java/project/myblog/documentation/Documentation.java
  src/test/java/project/myblog/documentation/auth/AuthDocumentation.java
  src/test/java/project/myblog/documentation/member/MemberDocumentation.java
  src/test/java/project/myblog/unit/member/MemberServiceTest.java
Labels: feat

#24 @ResponseStatus -> ResponseEntity로 통일
  src/main/java/project/myblog/web/MemberController.java
Labels: refactor

#28 exception structure
  src/main/java/project/myblog/auth/authentication/OAuthAuthentication.java
  src/main/java/project/myblog/auth/authorization/session/SessionAuthorization.java
  src/main/java/project/myblog/auth/dto/LoginMember.java
  src/main/java/project/myblog/domain/member/Member.java
  src/main/java/project/myblog/exception/AuthenticationException.java
  src/main/java/project/myblog/exception/AuthorizationException.java
  src/main/java/project/myblog/exception/BizException.java
  src/main/java/project/myblog/exception/ErrorController.java
  src/main/java/project/myblog/exception/ExceptionAdviceController.java
  src/main/java/project/myblog/exception/ExceptionCode.java
  src/main/java/project/myblog/exception/ExceptionController.java
  src/main/java/project/myblog/exception/ExceptionResponse.java
  src/main/java/project/myblog/exception/NotExistsMemberException.java
  src/main/java/project/myblog/repository/MemberRepository.java
  src/main/java/project/myblog/service/member/MemberService.java
  src/main/java/project/myblog/web/dto/member/response/MemberResponse.java
  src/test/java/project/myblog/acceptance/member/MemberAcceptance.java
  src/test/java/project/myblog/acceptance/member/MemberStepsAssert.java
  src/test/java/project/myblog/documentation/Documentation.java
  src/test/java/project/myblog/documentation/member/MemberDocumentation.java
  src/test/java/project/myblog/unit/member/MemberServiceTest.java
  src/test/java/project/myblog/unit/member/MemberTest.java
Labels: refactor

#36 DTO Bean Valdation 예외 메시지 개발
  .gitignore
  src/main/java/project/myblog/auth/authorization/session/SessionAuthorization.java
  src/main/java/project/myblog/config/FieldErrorDetail.java
  src/main/java/project/myblog/config/ValidationResult.java
  src/main/java/project/myblog/domain/member/Member.java
  src/main/java/project/myblog/exception/BusinessException.java
  src/main/java/project/myblog/exception/ExceptionAdviceController.java
  src/main/java/project/myblog/exception/ExceptionController.java
  src/main/java/project/myblog/exception/ExceptionResponse.java
  src/main/java/project/myblog/service/member/MemberService.java
  src/main/java/project/myblog/web/dto/member/request/MemberIntroductionRequest.java
  src/main/java/project/myblog/web/dto/member/request/MemberSubjectRequest.java
  src/main/resources/application-oauth.properties
  src/main/resources/application-oauth.yml
  src/main/resources/application.properties
  src/main/resources/application.yml
  src/main/resources/errors.properties
  src/test/java/project/myblog/acceptance/member/MemberAcceptance.java
  src/test/java/project/myblog/unit/member/MemberServiceTest.java
Labels: feat

#38 회원 탈퇴 후 재가입
  src/main/java/project/myblog/domain/BaseTimeEntity.java
  src/main/java/project/myblog/repository/MemberRepository.java
  src/main/java/project/myblog/service/member/MemberService.java
  src/test/java/project/myblog/unit/member/MemberServiceTest.java
Labels: feat

#39 포스트 작성 개발
  src/docs/asciidoc/index.adoc
  src/main/java/project/myblog/domain/post/Post.java
  src/main/java/project/myblog/repository/member/MemberRepository.java
  src/main/java/project/myblog/repository/post/PostRepository.java
  src/main/java/project/myblog/service/member/MemberService.java
  src/main/java/project/myblog/service/post/PostService.java
  src/main/java/project/myblog/web/MemberController.java
  src/main/java/project/myblog/web/PostController.java
  src/main/java/project/myblog/web/dto/post/PostRequest.java
  src/main/resources/static/docs/index.html
  src/test/java/project/myblog/acceptance/post/PostAcceptance.java
  src/test/java/project/myblog/acceptance/post/PostStepsAssert.java
  src/test/java/project/myblog/acceptance/post/PostStepsRequest.java
  src/test/java/project/myblog/documentation/post/PostDocumentation.java
  src/test/java/project/myblog/unit/member/MemberServiceTest.java
  src/test/java/project/myblog/unit/post/PostServiceTest.java
Labels: feat

#49 MvcMatcherInterceptor 개선
  src/main/java/project/myblog/auth/authentication/interceptor/MvcMatcherInterceptor.java
  src/main/java/project/myblog/auth/authentication/interceptor/MvcPatternInterceptor.java
  src/main/java/project/myblog/config/WebConfig.java
Labels: enhancement, refactor

#51 댓글 작성
  src/docs/asciidoc/index.adoc
  src/main/java/project/myblog/domain/Comment.java
  src/main/java/project/myblog/domain/Member.java
  src/main/java/project/myblog/domain/Post.java
  src/main/java/project/myblog/repository/CommentRepository.java
  src/main/java/project/myblog/service/CommentService.java
  src/main/java/project/myblog/service/PostService.java
  src/main/java/project/myblog/web/CommentController.java
  src/main/java/project/myblog/web/dto/comment/CommentRequest.java
  src/main/java/project/myblog/web/dto/post/PostRequest.java
  src/main/resources/application.properties
  src/main/resources/errors.properties
  src/main/resources/static/docs/index.html
  src/test/java/project/myblog/acceptance/comment/CommentAcceptance.java
  src/test/java/project/myblog/acceptance/comment/CommentStepsAssert.java
  src/test/java/project/myblog/acceptance/comment/CommentStepsRequest.java
  src/test/java/project/myblog/acceptance/member/MemberAcceptance.java
  src/test/java/project/myblog/documentation/CommentDocumentation.java
  src/test/java/project/myblog/unit/comment/CommentServiceTest.java
  src/test/java/project/myblog/unit/member/MemberServiceTest.java
  src/test/java/project/myblog/unit/post/PostServiceTest.java
Labels: feat

#52 댓글 조회
  src/docs/asciidoc/index.adoc
  src/main/java/project/myblog/domain/Comment.java
  src/main/java/project/myblog/repository/CommentRepository.java
  src/main/java/project/myblog/service/CommentService.java
  src/main/java/project/myblog/web/CommentController.java
  src/main/java/project/myblog/web/dto/comment/CommentResponse.java
  src/main/resources/static/docs/index.html
  src/test/java/project/myblog/acceptance/comment/CommentAcceptance.java
  src/test/java/project/myblog/acceptance/comment/CommentStepsAssert.java
  src/test/java/project/myblog/acceptance/comment/CommentStepsRequest.java
  src/test/java/project/myblog/documentation/CommentDocumentation.java
  src/test/java/project/myblog/documentation/Documentation.java
  src/test/java/project/myblog/documentation/PostDocumentation.java
  src/test/java/project/myblog/unit/comment/CommentServiceTest.java
Labels: feat

#53 댓글 수정
  src/docs/asciidoc/index.adoc
  src/main/java/project/myblog/domain/Comment.java
  src/main/java/project/myblog/exception/ExceptionCode.java
  src/main/java/project/myblog/service/CommentService.java
  src/main/java/project/myblog/service/PostService.java
  src/main/java/project/myblog/web/CommentController.java
  src/main/java/project/myblog/web/MemberController.java
  src/main/java/project/myblog/web/PostController.java
  src/main/resources/static/docs/index.html
  src/test/java/project/myblog/acceptance/comment/CommentAcceptance.java
  src/test/java/project/myblog/acceptance/comment/CommentStepsAssert.java
  src/test/java/project/myblog/acceptance/comment/CommentStepsRequest.java
  src/test/java/project/myblog/documentation/CommentDocumentation.java
  src/test/java/project/myblog/unit/comment/CommentServiceTest.java
  src/test/java/project/myblog/unit/comment/CommentTest.java
Labels: feat

#54 댓글 삭제
  src/docs/asciidoc/index.adoc
  src/main/java/project/myblog/exception/ExceptionCode.java
  src/main/java/project/myblog/service/CommentService.java
  src/main/java/project/myblog/web/CommentController.java
  src/main/resources/static/docs/index.html
  src/test/java/project/myblog/acceptance/comment/CommentAcceptance.java
  src/test/java/project/myblog/acceptance/comment/CommentStepsAssert.java
  src/test/java/project/myblog/acceptance/comment/CommentStepsRequest.java
  src/test/java/project/myblog/documentation/CommentDocumentation.java
  src/test/java/project/myblog/unit/comment/CommentServiceTest.java
  src/test/java/project/myblog/unit/post/PostServiceTest.java
Labels: feat

#62 대댓글 목록 조회
  src/docs/asciidoc/index.adoc
  src/main/java/project/myblog/domain/Comment.java
  src/main/java/project/myblog/repository/CommentRepository.java
  src/main/java/project/myblog/service/CommentService.java
  src/main/java/project/myblog/web/CommentController.java
  src/main/java/project/myblog/web/dto/comment/CommentRequest.java
  src/main/java/project/myblog/web/dto/comment/CommentResponse.java
  src/main/java/project/myblog/web/dto/comment/CommentResponses.java
  src/main/resources/static/docs/index.html
  src/test/java/project/myblog/acceptance/comment/CommentAcceptance.java
  src/test/java/project/myblog/acceptance/comment/CommentStepsAssert.java
  src/test/java/project/myblog/acceptance/comment/CommentStepsRequest.java
  src/test/java/project/myblog/documentation/CommentDocumentation.java
  src/test/java/project/myblog/unit/comment/CommentServiceTest.java
Labels: feat
